export enum EmployeeSortTypeEnum {

    ID_ASC = 'ID_ASC',
    INITIALS_ASC = 'INITIALS_ASC',
    INITIALS_DESC = 'INITIALS_DESC',
    PERSONNEL_NUMBER_ASC = 'PERSONNEL_NUMBER_ASC',
    PERSONNEL_NUMBER_DESC = 'PERSONNEL_NUMBER_DESC'

}
