package ru.kolaer.common.constant.assess;

public interface EmployeeAccessConstant extends CommonAccessConstant {
    String TYPE_WORKS_WRITE = PREFIX + "TYPE_WORKS_WRITE";
    String TYPE_WORKS_READ = PREFIX + "TYPE_WORKS_READ";

    String DEPARTMENTS_WRITE = PREFIX + "DEPARTMENTS_WRITE";

    String POSTS_WRITE = PREFIX + "POSTS_WRITE";

    String EMPLOYEES_READ = PREFIX + "EMPLOYEES_READ";
    String EMPLOYEES_READ_DEPARTMENT = PREFIX + "EMPLOYEES_READ_DEPARTMENT";
    String EMPLOYEES_WRITE = PREFIX + "EMPLOYEES_WRITE";
    String EMPLOYEES_SYNC = PREFIX + "EMPLOYEES_SYNC";
    String EMPLOYEES_REPORT_OLD = PREFIX + "EMPLOYEES_REPORT_OLD";

    String EMPLOYEE_WRITE = PREFIX + "EMPLOYEE_WRITE";

    String EMPLOYEE_TYPE_WORK_WRITE_DEPARTMENT = PREFIX + "EMPLOYEE_TYPE_WORK_WRITE_DEPARTMENT";

    String EMPLOYEE_EDUCATIONS_READ = PREFIX + "EMPLOYEE_EDUCATIONS_READ";
    String EMPLOYEE_ACHIEVEMENTS_READ = PREFIX + "EMPLOYEE_ACHIEVEMENTS_READ";
    String EMPLOYEE_EMPLOYMENT_HISTORIES_READ = PREFIX + "EMPLOYEE_EMPLOYMENT_HISTORIES_READ";
    String EMPLOYEE_MILITARY_REGISTRATIONS_READ = PREFIX + "EMPLOYEE_MILITARY_REGISTRATIONS_READ";
    String EMPLOYEE_PERSONAL_DATA_READ = PREFIX + "EMPLOYEE_PERSONAL_DATA_READ";
    String EMPLOYEE_PUNISHMENTS_READ = PREFIX + "EMPLOYEE_PUNISHMENTS_READ";
    String EMPLOYEE_RELATIVES_READ = PREFIX + "EMPLOYEE_RELATIVES_READ";
    String EMPLOYEE_STAFF_MOVEMENTS_READ = PREFIX + "EMPLOYEE_STAFF_MOVEMENTS_READ";
    String EMPLOYEE_PERSONAL_DOCUMENT_READ = PREFIX + "EMPLOYEE_PERSONAL_DOCUMENT_READ";
    String EMPLOYEE_COMBINATION_READ = PREFIX + "EMPLOYEE_COMBINATION_READ";

    String EMPLOYEE_EDUCATIONS_READ_DEPARTMENT = PREFIX + "EMPLOYEE_EDUCATIONS_READ_DEPARTMENT";
    String EMPLOYEE_ACHIEVEMENTS_READ_DEPARTMENT = PREFIX + "EMPLOYEE_ACHIEVEMENTS_READ_DEPARTMENT";
    String EMPLOYEE_EMPLOYMENT_HISTORIES_READ_DEPARTMENT = PREFIX + "EMPLOYEE_EMPLOYMENT_HISTORIES_READ_DEPARTMENT";
    String EMPLOYEE_MILITARY_REGISTRATIONS_READ_DEPARTMENT = PREFIX + "EMPLOYEE_MILITARY_REGISTRATIONS_READ_DEPARTMENT";
    String EMPLOYEE_PERSONAL_DATA_READ_DEPARTMENT = PREFIX + "EMPLOYEE_PERSONAL_DATA_READ_DEPARTMENT";
    String EMPLOYEE_PUNISHMENTS_READ_DEPARTMENT = PREFIX + "EMPLOYEE_PUNISHMENTS_READ_DEPARTMENT";
    String EMPLOYEE_RELATIVES_READ_DEPARTMENT = PREFIX + "EMPLOYEE_RELATIVES_READ_DEPARTMENT";
    String EMPLOYEE_STAFF_MOVEMENTS_READ_DEPARTMENT = PREFIX + "EMPLOYEE_STAFF_MOVEMENTS_READ_DEPARTMENT";
    String EMPLOYEE_PERSONAL_DOCUMENT_READ_DEPARTMENT = PREFIX + "EMPLOYEE_PERSONAL_DOCUMENT_READ_DEPARTMENT";
    String EMPLOYEE_COMBINATION_READ_DEPARTMENT = PREFIX + "EMPLOYEE_COMBINATION_READ_DEPARTMENT";
}
